### ISSUE TITLE
fatal error: UDP.h: No such file or directory

### ISSUE THREAD

**Issue by magskull** [RoboCore/Ethernet_W5500#1]
The file not exists...
How I can get then?

**Comment by RoboCore** [comment]
Which board did you select for compiling and for which version of the Arduino IDE? Did you try compiling one of the examples of the library, like <[WebServer.ino](https://github.com/RoboCore/Ethernet_W5500/blob/master/examples/WebServer/WebServer.ino)>?

**Comment by RoboCore** [comment]
Issue closed because it has been inactive for a few months. If the problem persists, please re-open the topic.
